# Generated by Django 3.0.3 on 2020-02-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='skill',
            name='contact',
        ),
        migrations.AddField(
            model_name='skill',
            name='contact',
            field=models.ManyToManyField(related_name='verified_skills', related_query_name='skills', to='contacts.Contact'),
        ),
    ]
