# Generated by Django 3.0.3 on 2020-02-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20200214_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
